'use strict';
/* Builds the GitHub Pages version into docs/.

   Same client code as the local app; the only difference is that static-api.js
   answers the /api/* routes from IndexedDB instead of a Node server.

   Run:  node tools/buildStatic.js
   Then: GitHub repo -> Settings -> Pages -> Source: main branch, /docs folder   */

const fs = require('node:fs');
const path = require('node:path');
const { build, resolveSource } = require('../lib/parseReadme');

const ROOT = path.join(__dirname, '..');
const PUBLIC = path.join(ROOT, 'public');
const OUT = path.join(ROOT, 'docs');

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

/* ---------- 1. bake the curriculum in ---------- */
const course = build(resolveSource(ROOT));
let items = 0;
const walk = (n) => { items += n.items.length; n.children.forEach(walk); };
course.sections.forEach(walk);
course.itemCount = items;

fs.writeFileSync(path.join(OUT, 'course-data.js'),
  'window.__COURSE__ = ' + JSON.stringify(course) + ';\n');

/* ---------- 2. copy the client ---------- */
for (const f of ['styles.css', 'app.js', 'md.js', 'static-api.js']) {
  fs.copyFileSync(path.join(PUBLIC, f), path.join(OUT, f));
}

/* ---------- 3. index.html: relative paths, no auth screen ---------- */
let html = fs.readFileSync(path.join(PUBLIC, 'index.html'), 'utf8');

// GitHub Pages serves from /<repo>/, so absolute paths would 404.
html = html.replace(/(href|src)="\/([^"]+)"/g, '$1="$2"');

// Load the baked data and the adapter before the app.
html = html.replace('<script src="md.js"></script>',
  '<script src="course-data.js"></script>\n<script src="md.js"></script>\n' +
  '<script src="static-api.js"></script>');

// The auth gate can never succeed without a server; drop it entirely.
html = html.replace(/<!-- =+ AUTH =+ -->[\s\S]*?<\/section>\s*/,
  '<!-- auth removed: the static build has no server and no accounts -->\n\n');

// A short note so a visitor understands whose data they are looking at.
html = html.replace('</head>',
  '<meta name="description" content="A free, emulator-first syllabus for embedded software ' +
  'engineering: 13 stages, project gates, and a progress tracker that runs entirely in your browser.">\n' +
  '<meta name="color-scheme" content="dark light">\n</head>');

fs.writeFileSync(path.join(OUT, 'index.html'), html);

/* ---------- 4. Pages housekeeping ---------- */
fs.writeFileSync(path.join(OUT, '.nojekyll'), '');
fs.copyFileSync(path.join(ROOT, 'SYLLABUS.md'), path.join(OUT, 'SYLLABUS.md'));

fs.writeFileSync(path.join(OUT, 'README.md'), [
  '# Embedded Software Syllabus — hosted build',
  '',
  'Generated by `node tools/buildStatic.js`. **Do not edit anything in this folder by hand** —',
  'it is overwritten on every build. Edit `tools/syllabusMap.js` or `public/` instead.',
  '',
  'Progress, notes and reminders are stored in the visitor\'s own browser (IndexedDB). There is no',
  'server, no account and no data leaves the machine.',
  '',
  'The syllabus is a derivative of',
  '[m3y54m/embedded-engineering-roadmap](https://github.com/m3y54m/embedded-engineering-roadmap)',
  'and is licensed [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).',
  '',
].join('\n'));

/* ---------- report ---------- */
const size = (f) => (fs.statSync(path.join(OUT, f)).size / 1024).toFixed(0) + ' kB';
console.log('static build -> docs/\n');
for (const f of fs.readdirSync(OUT).sort()) {
  if (f === '.nojekyll') continue;
  console.log('  ' + size(f).padStart(8) + '  ' + f);
}
console.log('\n  ' + course.sections.length + ' chapters, ' + items + ' items baked in');
console.log('\nnext: commit docs/, then Settings -> Pages -> main branch, /docs folder');
