'use strict';
/* The curriculum: which source material lands in which stage, in what order.
   `road` entries name sections of sources/embedded-engineering-roadmap.md by the
   tail of their heading path. `legacy` entries name topics of README.md.
   Everything here is a deliberate editorial choice — the build script only
   executes it. */

module.exports = {
  // Paid links are stripped everywhere except these three canonical books.
  allowPaid: [
    'The C Programming Language',
    'Test Driven Development for Embedded C',
    'Making Embedded Systems',
  ],

  // Verified dead by tools/checkLinks.js — removed at build time rather than by
  // hand-editing SYLLABUS.md, so a rebuild keeps them out. Re-run the checker to
  // refresh this list.
  deadLinks: [
    // Removed / private YouTube videos
    'yt:C7tze29hhpc', 'yt:ikMHep5oT5w', 'yt:RVM-ESUMOMU', 'yt:HF7Low_sUig',
    'yt:dzR6DD3ClZ4', 'yt:r9f7oVgYoMk', 'yt:zzkcX-0mMHU', 'yt:TO66UN64-os',
    'yt:U9phLv8gS8',
    // Pages that now 404
    'dockerlabs.collabnix.com/docker/cheatsheet',
    'riscv.org/community/learn-about-risc-v/educational-materials',
    'docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/bluetooth.html',
    'thirtythreeforty.net/series/mastering-embedded-linux',
    'passlab.github.io/openmpprogrammingbook/index.html',
    'blog.sourcerer.io/writing-a-simple-linux-kernel-module-d9dc3762c234',
  ],

  // Whole roadmap areas that belong to hardware engineering, not this course.
  drop: [
    'Electronics', 'Prototyping Skills', 'FPGA Development', 'Sensors & Actuators',
    'Search and Ask!', 'Multimeter', 'Breadboarding', 'Basic Discrete Mathematics',
    'Appendix-A: Advanced Topics', 'SVN (Subversion)', 'Career Development',
  ],

  stages: [
    /* ================= STAGE 0 ================= */
    {
      title: 'Stage 0 — Orientation & Your Emulated Lab',
      blurb: 'No board required. Set up a toolchain, an emulator and version control, and get ' +
        'something running before you learn any theory.',
      topics: [
        { title: 'What Embedded Systems Are',
          road: ["Don't Know Where to Start! > Other Helpful Roadmaps"],
          plus: [
            { title: 'Embedded Systems Roadmap: Bridging the Gap', type: 'Article', source: 'Memfault Interrupt',
              url: 'https://interrupt.memfault.com/blog/embedded-systems-roadmap-bridging-the-gap', beginner: true },
          ] },
        { title: 'Emulators & Simulators (your hardware)',
          road: ['Hardware Simulation / Emulation'],
          plus: [
            { title: 'Wokwi — browser simulator for ESP32, STM32, Pi Pico and Arduino', type: 'Link',
              source: 'Wokwi', url: 'https://wokwi.com/', beginner: true },
            { title: 'Wokwi Documentation', type: 'Link', source: 'Wokwi', url: 'https://docs.wokwi.com/' },
          ] },
        { title: 'Renode', road: ['Hardware Simulation / Emulation > Renode'] },
        { title: 'QEMU', road: ['Hardware Simulation / Emulation > QEMU'] },
        { title: 'Editors, IDEs & PlatformIO',
          road: ["Don't Know Where to Start! > IDEs", "Don't Know Where to Start! > VS Code Extensions",
                 "Don't Know Where to Start! > PlatformIO"],
          legacy: ['Development Environment > Development Tools > IDE'], shelf: true },
        { title: 'Git', road: ['Version Control Systems > Git'] },
        { title: 'The Shell', road: ['Build System > Bash Scripting'] },
        { title: 'Where to Look Things Up',
          road: ["Don't Know Where to Start! > Educational Websites"], shelf: true },
        { title: 'Starter Projects',
          road: ["Don't Know Where to Start! > Projects", "Don't Know Where to Start! > Arduino"], shelf: true },
        { project: {
                  name: 'Bring-Up: A Repo Anyone Can Run',
                  goal: 'Start the one repository every later stage adds to. A stranger clones it, runs one command, and watches your firmware boot in an emulator - no hardware, no setup.',
                  brief: [
                    '**What you are building**',
                    '',
                    'The skeleton of **cellguard** - an emulated battery-management node you will grow across every',
                    'stage. Today it does one thing: boots on a simulated Cortex-M and prints over UART.',
                    '',
                    'Every later gate adds a layer to *this* repo. By Stage 6 it is a single deep project rather than',
                    'eleven abandoned folders.',
                    '',
                    '**Why this is worth showing**',
                    '',
                    'Almost every embedded portfolio says "I blinked an LED on an STM32" and the reviewer cannot check.',
                    'Yours runs in twenty seconds on their laptop with no board. That alone puts you in a small',
                    'minority, and it is the reason the emulator-first choice pays off.',
                    '',
                    '**Expected output**',
                    '',
                    '```text',
                    '$ make run',
                    'Renode 1.15  |  platform: stm32f4_discovery',
                    '--------------------------------------------',
                    'cellguard v0.1.0  (build 2026-09-04 a1b2c3d)',
                    'sys: HSI 16 MHz, tick 1 kHz',
                    'led: heartbeat on PD12',
                    '--------------------------------------------',
                    '```',
                    '',
                    'And a repo a stranger can navigate:',
                    '',
                    '```text',
                    'cellguard/',
                    '  README.md          <- one screenshot, one command, what it is',
                    '  Makefile           <- make build | run | test | clean',
                    '  src/main.c',
                    '  boards/stm32f4.resc <- Renode script',
                    '  .github/workflows/ci.yml',
                    '```',
                    '',
                    '**What makes it stand out**',
                    '',
                    'The README. One GIF or screenshot of the emulator booting, a single copy-paste command, and two',
                    'sentences on what the project becomes. Reviewers spend thirty seconds on a repo - spend your effort',
                    'on those thirty seconds.',
                  ].join('\n'),
                  criteria: [
                    'Create the cellguard repo with a README that shows one command to run it',
                    'Blink an LED in Wokwi and link the shareable simulation from the README',
                    'Boot a Cortex-M binary in Renode from a checked-in .resc platform script',
                    'Print a version + build banner over UART so the boot is visibly yours',
                    'Add a make target set: build, run, test, clean',
                    'Tag it v0.1.0 so the history shows deliberate milestones',
                  ],
                }},
      ],
    },

    /* ================= STAGE 1 ================= */
    {
      title: 'Stage 1 — C for Embedded Systems',
      blurb: 'The language as it is actually used on a microcontroller: memory you own, ' +
        'hardware you address, and no runtime to save you.',
      topics: [
        { title: 'Learning C', road: ['Programming Languages > C'] },
        { title: 'Pointers & Memory Model',
          road: ['Programming Fundamentals > Memory Management'],
          legacy: ['Embedded Software > Pointers', 'Embedded Software > Memory Alignment',
                   'Embedded Hardware > Constraints > Memory'] },
        { title: 'The Keywords That Matter',
          legacy: ['Embedded Software > C Keywords'] },
        { title: 'Bit Manipulation',
          legacy: ['Embedded Software > Bit Manipulation'] },
        { title: 'Concepts Worth Internalising',
          legacy: ['Embedded Software > Important Programming Concepts (Even on Embedded Systems)'] },
        { title: 'Data Structures for Constrained Systems',
          road: ['Programming Fundamentals > Algorithms & Data Structures'],
          legacy: ['Embedded Software Layers > Application Layer > Data Structures and Algorithms > Queue > Circular Buffer'] },
        { title: 'A Little Assembly', road: ['Programming Languages > Assembly'] },
        { project: {
                  name: 'libcore: The Foundation, Tested On Your PC',
                  goal: 'Write the small allocation-free library the rest of the firmware stands on, and prove it with tests that run on your laptop in milliseconds.',
                  brief: [
                    '**What you are building**',
                    '',
                    '`libcore` inside cellguard: a **lock-free ring buffer**, **fixed-point maths**, and a **CRC-16**.',
                    'Pure C99, zero dynamic allocation, no hardware dependencies - so it compiles and tests on the host.',
                    '',
                    'These three are not busywork: the ring buffer carries your UART and CAN traffic in Stage 4, the',
                    'fixed-point type holds cell voltages without an FPU, and the CRC guards your firmware images in',
                    'Stage 6.',
                    '',
                    '**Why this is worth showing**',
                    '',
                    '"No `malloc` and here are the tests" is the sentence that separates an embedded engineer from a',
                    'programmer who happens to use C. Host-testable driver-free logic is also what makes Stage 6\'s CI',
                    'possible at all.',
                    '',
                    '**Expected output**',
                    '',
                    '```c',
                    '/* ringbuf.h - fixed capacity, single producer, single consumer */',
                    'typedef struct { uint8_t *buf; uint16_t head, tail, mask; } rb_t;',
                    '',
                    'bool     rb_init(rb_t *rb, uint8_t *storage, uint16_t size_pow2);',
                    'bool     rb_put(rb_t *rb, uint8_t byte);      /* false when full  */',
                    'bool     rb_get(rb_t *rb, uint8_t *out);      /* false when empty */',
                    'uint16_t rb_used(const rb_t *rb);',
                    '```',
                    '',
                    '```text',
                    '$ make test',
                    'libcore: 41 tests, 41 passed, 0 failed   (18 ms)',
                    '  ringbuf ......... 14 passed   (wrap, full, empty, ISR interleave)',
                    '  fixed ........... 19 passed   (saturation, rounding, div-by-zero)',
                    '  crc16 ...........  8 passed   (known vectors, incremental)',
                    'lines covered: 96.4%',
                    '```',
                    '',
                    '**What makes it stand out**',
                    '',
                    'Put the **saturation and wrap-around edge cases** in the test names and show the coverage number in',
                    'the README. Then add one paragraph: *why* single-producer/single-consumer needs no lock on a',
                    'Cortex-M, and exactly which assumption breaks if a second producer appears. Judgement shown beats',
                    'code shown.',
                  ].join('\n'),
                  criteria: [
                    'Write a fixed-capacity ring buffer with no dynamic allocation',
                    'Make it correct for one ISR producer and one main-loop consumer without a lock',
                    'Write a Q15 or Q16.16 fixed-point type with saturating add, multiply and divide',
                    'Add a CRC-16 you will reuse for firmware image validation in Stage 6',
                    'Cover wrap-around, full, empty and saturation explicitly in host tests',
                    'Report a coverage percentage in the README',
                    'Document why the lock-free claim holds, and the assumption that would break it',
                    'Compile clean at -Wall -Wextra -Werror -std=c99',
                  ],
                }},
      ],
    },

    /* ================= STAGE 2 ================= */
    {
      title: 'Stage 2 — Toolchain, Build System & Debugging',
      blurb: 'What you actually spend your day doing. Most self-taught engineers skip this ' +
        'and stay stuck at "it works on my machine".',
      topics: [
        { title: 'Cross Compilation & GCC',
          road: ['Build System > Compilers / GCC'],
          legacy: ['Development Environment > Cross Compilation'] },
        { title: 'From Zero to main() — how firmware actually starts',
          plus: [
            { title: 'From Zero to main(): Bare metal C', type: 'Article', source: 'Memfault Interrupt',
              url: 'https://interrupt.memfault.com/blog/zero-to-main-1', gem: true },
            { title: 'From Zero to main(): Bootstrapping libc with Newlib', type: 'Article',
              source: 'Memfault Interrupt', url: 'https://interrupt.memfault.com/blog/boostrapping-libc-with-newlib' },
            { title: 'From Zero to main(): Demystifying Firmware Linker Scripts', type: 'Article',
              source: 'Memfault Interrupt', url: 'https://interrupt.memfault.com/blog/how-to-write-linker-scripts-for-firmware', gem: true },
          ] },
        { title: 'Make & CMake', road: ['Build System > Make / CMake'] },
        { title: 'Reproducible Builds with Docker', road: ['Build System > Docker'] },
        { title: 'GDB', road: ['Debugging > GDB'] },
        { title: 'JTAG & SWD', road: ['Debugging > JTAG / SWD', 'Debugging'] },
        { title: 'OpenOCD', road: ['Debugging > OpenOCD'] },
        { title: 'Reading the Bus — scopes & analyzers',
          road: ['Using Test Equipment > Logic / Protocol Analyzer', 'Using Test Equipment > Oscilloscope'],
          legacy: ['Debugging > Logic Analyzer', 'Debugging > Oscilliscope'] },
        { project: {
                  name: 'Reproducible Build, Readable Memory Map',
                  goal: 'Take full control of how the binary is produced and where every byte lands - then make it build identically on any machine.',
                  brief: [
                    '**What you are building**',
                    '',
                    'The build system for cellguard: cross-compilation, **your own linker script**, a Docker image that',
                    'reproduces the build anywhere, and a memory report printed on every build.',
                    '',
                    '**Why this is worth showing**',
                    '',
                    'Ask a mid-level candidate what their linker script does and most cannot answer. A repo with a',
                    'commented linker script and a `make size` table showing exactly where flash and RAM went is',
                    'immediate evidence of the level you are at. The Docker image also means the reviewer\'s build',
                    'matches yours - no "works on my machine".',
                    '',
                    '**Expected output**',
                    '',
                    '```text',
                    '$ make size',
                    '   text     data      bss      dec    flash%   ram%',
                    '  18 432      112    4 096   22 640    3.5%    1.2%',
                    '',
                    '  .isr_vector   0x08000000    428 B',
                    '  .text         0x080001ac  18 004 B',
                    '  .rodata       0x08004800   1 240 B',
                    '  .data         0x20000000    112 B   (load 0x08004cd8)',
                    '  .bss          0x20000070  4 096 B',
                    '  stack top     0x20020000',
                    '```',
                    '',
                    '```text',
                    '$ docker run --rm -v $PWD:/w cellguard-build make -C /w build',
                    '# byte-identical binary to the local build:',
                    '$ sha256sum build/cellguard.elf',
                    '9f2c...e41  build/cellguard.elf',
                    '```',
                    '',
                    '**What makes it stand out**',
                    '',
                    'A `docs/memory.md` that walks the boot path in your own words: reset vector, `.data` copied from',
                    'flash to RAM, `.bss` zeroed, stack pointer set, `main()` entered. Link each step to the line in',
                    '*your* startup file. That document is worth more in an interview than the code.',
                  ].join('\n'),
                  criteria: [
                    'Cross-compile to ARM from a Makefile or CMakeLists you wrote yourself',
                    'Write and comment your own linker script - do not copy a vendor one blindly',
                    'Add a make size target that reports text/data/bss and flash/RAM percentage',
                    'Reproduce the exact same binary inside a Docker image and check the hash',
                    'Write docs/memory.md tracing reset vector to main() through your startup code',
                    'Attach GDB to QEMU or Renode, break inside an ISR and inspect the stack',
                    'Record the exact debug commands in the README so a reviewer can repeat them',
                  ],
                }},
      ],
    },

    /* ================= STAGE 3 ================= */
    {
      title: 'Stage 3 — Bare-Metal Microcontroller Programming',
      blurb: 'Datasheet to working driver, with no HAL in between. This is the core skill.',
      topics: [
        { title: 'Microcontroller Fundamentals',
          road: ['Microcontrollers'],
          legacy: ['Embedded Hardware > Computer Architecture', 'Embedded Hardware > Embedded Platforms'] },
        { title: 'Registers, Memory Maps & Peripherals',
          legacy: ['Embedded Software Layers > Peripheral and Hardware Layer'] },
        { title: 'GPIO', road: ['Microcontrollers > GPIO'], legacy: ['Embedded Hardware > GPIO'] },
        { title: 'Interrupts', road: ['Microcontrollers > Interrupts'],
          legacy: ['Embedded Software > Interrupts'] },
        { title: 'Timers & Counters', road: ['Microcontrollers > Timers / Counters', 'Microcontrollers > RTC (Real Time Clock)'],
          legacy: ['Embedded Hardware > Timer'] },
        { title: 'PWM', road: ['Microcontrollers > PWM (Pulse Width Modulation)'],
          legacy: ['Embedded Hardware > Analog Output > PWM'] },
        { title: 'ADC & DAC', road: ['Microcontrollers > ADC', 'Microcontrollers > DAC'],
          legacy: ['Embedded Hardware > Analog Input', 'Embedded Hardware > Analog Output > DAC'] },
        { title: 'DMA', road: ['Microcontrollers > DMA'] },
        { title: 'Clock Management', road: ['Microcontrollers > Clock Management'] },
        { title: 'Watchdog', road: ['Microcontrollers > Watchdog'],
          legacy: ['Embedded Software > Watchdog Timer'] },
        { title: 'Low Power Design', road: ['Microcontrollers > Power Management'],
          legacy: ['Embedded Hardware > Constraints > Power'] },
        { title: 'Memory Technologies',
          road: ['Memory Technologies & File Systems > Flash Memory', 'Memory Technologies & File Systems > Flash Memory > NOR / NAND',
                 'Memory Technologies & File Systems > EEPROM', 'Memory Technologies & File Systems > SRAM / DRAM'] },
        { title: 'HAL, BSP & Driver Architecture',
          legacy: ['Embedded Software Layers > Hardware Abstraction Layer'] },
        { title: 'Register-Level Drills (MSP430 walkthroughs)',
          legacy: ['Embedded Hardware > GPIO > Direction', 'Embedded Hardware > Timer > MSP430 Timer',
                   'Embedded Hardware > Analog Input > ADC > Analog-to-Digital Converter on the MSP430',
                   'Embedded Software > Interrupts > MSP430 Interrupts'], shelf: true },
        { project: {
                  name: 'Bare-Metal Drivers, Written From The Manual',
                  goal: 'Write the peripheral drivers from the reference manual alone - no vendor HAL, no copied example - and show the register evidence for every line.',
                  brief: [
                    '**What you are building**',
                    '',
                    'cellguard\'s hardware layer: **GPIO**, a **periodic timer interrupt**, an **ADC read**, and a',
                    '**DMA transfer**, all driven by writes to registers you looked up yourself in the reference manual.',
                    '',
                    'The ADC becomes your cell-voltage sampler; the timer becomes the control tick; DMA is what keeps',
                    'the CPU free while sampling.',
                    '',
                    '**Why this is worth showing**',
                    '',
                    '"Configure this peripheral from the datasheet" is *the* embedded interview exercise. A repo where',
                    'each driver links to the manual section and register it came from proves you can do it before',
                    'anyone asks.',
                    '',
                    '**Expected output**',
                    '',
                    '```c',
                    '/* adc.c - STM32F4 RM0090 s13.13.2, ADC_CR2 */',
                    'void adc_init(void) {',
                    '    RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;      /* RM0090 s6.3.11 */',
                    '    ADC1->SMPR2   = ADC_SMPR2_SMP0_2;        /* 84 cycles - Rsource < 10k */',
                    '    ADC1->CR2     = ADC_CR2_ADON;            /* RM0090 s13.13.3 */',
                    '}',
                    '```',
                    '',
                    'And a `docs/registers.md` table a reviewer can audit:',
                    '',
                    '| Peripheral | Register | Field | Value | Manual |',
                    '|---|---|---|---|---|',
                    '| ADC1 | SMPR2 | SMP0 | 0b100 | RM0090 §13.13.5 |',
                    '| TIM2 | PSC | - | 15999 | RM0090 §18.4.11 |',
                    '',
                    '```text',
                    '$ make run',
                    'tick: 1000 Hz  (measured 999.98 Hz over 60 s)',
                    'adc: dma ring 64 samples, cpu idle 98.7% during conversion',
                    '```',
                    '',
                    '**What makes it stand out**',
                    '',
                    'The measurement. Anyone can claim a 1 kHz tick; showing it measured at 999.98 Hz over a minute, and',
                    'the CPU idle percentage during DMA, is the difference between "I wrote a driver" and "I verified a',
                    'driver".',
                  ].join('\n'),
                  criteria: [
                    'Write a GPIO driver from the reference manual with no vendor HAL',
                    'Add a timer that raises a periodic interrupt at a rate you choose',
                    'Handle that interrupt and prove the rate by measuring it over 60 seconds',
                    'Read the ADC and stream conversions into a ring buffer using DMA',
                    'Show CPU idle time during DMA to prove the transfer is not CPU-driven',
                    'Keep docs/registers.md linking every field you set to its manual section',
                    'Make the whole hardware layer swappable behind a header so Stage 6 can mock it',
                  ],
                }},
      ],
    },

    /* ================= STAGE 4 ================= */
    {
      title: 'Stage 4 — Buses, Protocols & Connectivity',
      blurb: 'Every embedded product talks to something. UART, SPI and I²C first, then CAN — ' +
        'the backbone of automotive and battery systems.',
      topics: [
        { title: 'Serial Communication Overview',
          road: ['Basic Protocols'],
          legacy: ['Embedded Hardware > Serial Communication'] },
        { title: 'UART', road: ['Basic Protocols > UART'],
          legacy: ['Embedded Hardware > Serial Communication > UART > UART on the MSP430',
                   'Embedded Hardware > Serial Communication > RS232'] },
        { title: 'SPI', road: ['Basic Protocols > SPI'],
          legacy: ['Embedded Hardware > Serial Communication > SPI > SPI on the MSP430'] },
        { title: 'I2C', road: ['Basic Protocols > I2C', 'Basic Protocols > I3C', 'Basic Protocols > 1-Wire'],
          legacy: ['Embedded Hardware > Serial Communication > I2C > I2C on the MSP430'] },
        { title: 'CAN & CAN FD', road: ['Automotive Protocols > CAN'] },
        { title: 'RS-485 & Modbus',
          road: ['Industrial Protocols > Modbus', 'Industrial Protocols > RS485'],
          legacy: ['Embedded Hardware > Serial Communication > RS485'] },
        { title: 'USB', road: ['High-Speed Protocols > USB'] },
        { title: 'Ethernet & Sockets',
          road: ['High-Speed Protocols > Ethernet',
                 'Interfaces, Protocols & Communication Technologies > Network Protocols / Socket Programming'] },
        { title: 'Bluetooth & BLE', road: ['Wireless Protocols > Bluetooth / BLE'] },
        { title: 'Wi-Fi', road: ['Wireless Protocols > Wi-Fi'] },
        { title: 'MQTT & CoAP', road: ['Industrial Protocols > CoAP & MQTT'] },
        { title: 'Long-Range & Mesh (LoRa, Zigbee, Thread, Matter)',
          road: ['Wireless Protocols > LoRa / LoRaWAN', 'Wireless Protocols > Zigbee',
                 'Wireless Protocols > Thread', 'Wireless Protocols > Matter'], shelf: true },
        { title: 'SD Cards & File Systems',
          road: ['Flash Memory > SD Card', 'Flash Memory > eMMC', 'Basic Protocols > SDIO',
                 'Memory Technologies & File Systems > File Systems'] },
        { project: {
                  name: 'Sensing and CAN: The Part Employers Recognise',
                  goal: 'Give cellguard a voice on the bus that every vehicle uses, and a driver that survives a sensor misbehaving.',
                  brief: [
                    '**What you are building**',
                    '',
                    'An **I2C driver for a battery front-end** (voltages and temperature) with real error handling, and',
                    'a **CAN layer** that encodes and decodes a small DBC-style message set with proper signal packing -',
                    'scale, offset, endianness, signedness.',
                    '',
                    'Then you fuzz the decoder until it cannot be crashed.',
                    '',
                    '**Why this is worth showing**',
                    '',
                    'CAN with correct signal packing is directly employable in automotive, EV and industrial work, and',
                    'it is the single most recognisable skill on this list. The fuzzing is what makes it senior: most',
                    'candidates decode the happy path and stop.',
                    '',
                    '**Expected output**',
                    '',
                    '```text',
                    '$ ./tools/candump-replay logs/pack_charge.log',
                    '0x18F001 [8]  22 01 A4 06 32 00 00 7F',
                    '  -> CellVoltage_01 = 3.874 V   (raw 0x0122, scale 0.001, offset 0)',
                    '  -> PackCurrent    = -12.4 A   (raw 0x06A4, signed, scale 0.1)',
                    '  -> PackTemp       = 25.0 C    (raw 0x32,   offset -40)',
                    '  -> State          = CHARGING',
                    '',
                    '$ make fuzz',
                    '24 000 malformed frames in 3.2 s: 0 crashes, 0 out-of-bounds reads',
                    '  truncated ....... 8 000 rejected cleanly',
                    '  bad DLC ......... 8 000 rejected cleanly',
                    '  garbage payload . 8 000 decoded to clamped values',
                    '```',
                    '',
                    '**What makes it stand out**',
                    '',
                    'Handle the ugly cases and say so in the README: an I2C slave that NAKs forever, a bus stuck low, a',
                    'sensor returning 0xFFFF. Show that the driver reports an error and the system keeps running instead',
                    'of hanging. **Never hanging** is the property that gets firmware shipped.',
                  ].join('\n'),
                  criteria: [
                    'Write an I2C driver for a battery front-end that never blocks forever',
                    'Handle NAK, bus-busy and timeout explicitly, returning errors to the caller',
                    'Define a small CAN message set with scale, offset, endianness and sign',
                    'Encode and decode it with a round-trip test for every signal',
                    'Fuzz the decoder with truncated, wrong-DLC and garbage frames - zero crashes',
                    'Replay a recorded CAN log and print decoded engineering values',
                    'Document the failure behaviour of every sensor error path in the README',
                  ],
                }},
      ],
    },

    /* ================= STAGE 5 ================= */
    {
      title: 'Stage 5 — RTOS & Firmware Architecture',
      blurb: 'Once one loop is not enough: scheduling, concurrency, and how to structure ' +
        'firmware so it survives its second year.',
      topics: [
        { title: 'Operating System Fundamentals',
          road: ['Operating Systems > Operating System Fundamentals'],
          legacy: ['Embedded Operating Systems > Bare Metal'] },
        { title: 'RTOS Concepts', road: ['Real-Time Operating Systems > RTOS Basics'],
          legacy: ['Embedded Operating Systems > Real Time Operating Systems'] },
        { title: 'FreeRTOS', road: ['Real-Time Operating Systems > FreeRTOS'] },
        { title: 'Zephyr', road: ['Real-Time Operating Systems > Zephyr'] },
        { title: 'Other RTOSes Worth Knowing',
          road: ['Real-Time Operating Systems > NuttX', 'Real-Time Operating Systems > RT-Thread',
                 'Real-Time Operating Systems > μC/OS / Micriμm OS', 'Real-Time Operating Systems > Mbed OS',
                 'Real-Time Operating Systems > Azure RTOS (ThreadX)', 'Real-Time Operating Systems > QNX',
                 'Real-Time Operating Systems > VxWorks'], shelf: true },
        { title: 'Concurrency Primitives',
          legacy: ['Embedded Software Layers > Application Layer > Data Structures and Algorithms > Queue > Semaphore',
                   'Embedded Software Layers > Application Layer > Data Structures and Algorithms > Queue > Producer-Consumer'] },
        { title: 'State Machines & Event-Driven Design',
          road: ['Programming Fundamentals > State Machines'],
          legacy: ['Embedded Software Layers > Application Layer > Data Structures and Algorithms > Queue > Event Handling'] },
        { title: 'Design Patterns for Firmware',
          road: ['Programming Fundamentals > Design Patterns'] },
        { title: 'Embedded GUI', road: ['Embedded GUI'] },
        { project: {
                  name: 'RTOS Architecture You Can Defend',
                  goal: 'Restructure cellguard into tasks and prove you understand scheduling - by causing a priority inversion on purpose, measuring it, and fixing it.',
                  brief: [
                    '**What you are building**',
                    '',
                    'cellguard moves from a superloop to an **RTOS**: a sampling task, a CAN task, a control task and a',
                    'logger, communicating only through queues. Then you size every stack from measured evidence rather',
                    'than guesswork.',
                    '',
                    '**Why this is worth showing**',
                    '',
                    '"I used FreeRTOS" is on every CV. **"Here is the priority inversion I induced, the trace showing',
                    'the deadline miss, and the mutex change that fixed it"** is on almost none. That single',
                    'demonstration is worth more than the rest of the stage.',
                    '',
                    '**Expected output**',
                    '',
                    'A task table in the README, justified rather than guessed:',
                    '',
                    '| Task | Prio | Period | Stack used / allocated | Worst latency |',
                    '|---|---:|---:|---:|---:|',
                    '| adc_sample | 4 | 1 ms | 412 / 768 B | 180 us |',
                    '| can_tx | 3 | 10 ms | 508 / 1024 B | 1.2 ms |',
                    '| control | 2 | 20 ms | 640 / 1024 B | 3.8 ms |',
                    '| logger | 1 | idle | 320 / 512 B | - |',
                    '',
                    '```text',
                    '$ make demo-inversion',
                    '[  0.000] control (prio 2) takes sensor_mutex',
                    '[  0.002] adc_sample (prio 4) blocks on sensor_mutex',
                    '[  0.041] logger (prio 1) preempts control  <-- inversion',
                    '[  0.043] adc_sample DEADLINE MISSED by 39 ms',
                    '--- enabling priority inheritance ---',
                    '[  0.002] adc_sample blocks; control boosted 2 -> 4',
                    '[  0.003] adc_sample runs. worst latency 1.1 ms. no misses.',
                    '```',
                    '',
                    '**What makes it stand out**',
                    '',
                    'Stack high-water marks. Reporting *used vs allocated* proves you measured instead of picking 1024',
                    'because it looked safe - and it is a number a reviewer can immediately trust.',
                  ].join('\n'),
                  criteria: [
                    'Restructure the firmware into RTOS tasks with explicit priorities and periods',
                    'Make tasks communicate only through queues - no shared globals',
                    'Measure stack high-water marks and size every stack from that evidence',
                    'Induce a priority inversion deliberately and capture the deadline miss',
                    'Fix it with priority inheritance and show the before/after trace',
                    'Publish the task table with worst-case latency in the README',
                    'Justify every priority choice in one line each',
                  ],
                }},
      ],
    },

    /* ================= STAGE 6 ================= */
    {
      title: 'Stage 6 — Production Firmware Engineering',
      blurb: 'The gap between hobby firmware and shipped firmware: tests, CI, updates, ' +
        'safety and security.',
      topics: [
        { title: 'Testing Embedded Software', road: ['Learning Resources > Testing'] },
        { title: 'Test-Driven Development',
          road: ['Testing > Test Driven Development (TDD)'] },
        { title: 'Unit Testing & Mocking',
          road: ['Test Driven Development (TDD) > Unit Testing',
                 'Unit Testing > GoogleTest - Google Testing and Mocking Framework'] },
        { title: 'Integration, SIL & HIL Testing',
          road: ['Test Driven Development (TDD) > Integration Testing', 'Testing > SIL / HIL Testing'] },
        { title: 'CI/CD for Firmware', road: ['Testing > CI/CD Pipelines'] },
        { title: 'Coding Standards, MISRA & Static Analysis',
          road: ['Testing > Standards & Certifications'],
          legacy: ['Embedded Software > Coding Standards', 'Debugging > Static Analysis',
                   'Embedded Software > Optimizations'] },
        { title: 'Functional Safety', road: ['Standards & Certifications > Functional Safety'] },
        { title: 'Bootloaders & Firmware Update',
          road: ['Microcontrollers > Bootloader / DFU (Device Firmware Update)',
                 'IoT (Internet of Things) > Delta Over-The-Air Firmware Update',
                 'IoT (Internet of Things)'] },
        { title: 'Cryptography for Devices', road: ['Embedded Security > Cryptography'],
          legacy: ['Embedded Software Layers > Application Layer > Domain Knowledge > Cryptography and Encryption'] },
        { title: 'Secure Boot & Signed Updates', road: ['Embedded Security > Secure Boot & Secure Firmware Update'] },
        { title: 'Attacking Your Own Device',
          road: ['Embedded Security > Hardware Hacking', 'Learning Resources > Embedded Security'] },
        { title: 'How Firmware Teams Work',
          road: ['Software Development Life Cycle (SDLC) Models', 'Software Development Life Cycle (SDLC) Models > Agile / SCRUM',
                 'Software Development Life Cycle (SDLC) Models > V-Model (V-cycle)', 'Learning Resources > Soft Skills'] },
        { title: 'Quality & Testing Lectures',
          legacy: ['Testing and Quality Management > Phil Koopman Lectures'] },
        { project: {
                  name: 'The Flagship: CI-Tested Firmware With Signed Updates',
                  goal: 'Turn cellguard into something that looks shipped: tests written first, an emulator running them on every push, and a signed A/B update that refuses a tampered image.',
                  brief: [
                    '**What you are building**',
                    '',
                    'The stage that makes the whole repo a portfolio piece rather than a learning exercise:',
                    '',
                    '- the I2C and CAN layers **rebuilt test-first** against a mocked bus',
                    '- **GitHub Actions** running unit tests *and* a full Renode boot on every push',
                    '- static analysis in the pipeline',
                    '- an **A/B bootloader** that verifies a signature before switching banks',
                    '',
                    '**Why this is worth showing**',
                    '',
                    'This is the differentiator. Firmware CI that boots the actual image in an emulator on every commit',
                    'is something many working teams do not have. A green badge on your README, backed by a workflow a',
                    'reviewer can read, says more about your engineering maturity than any amount of driver code.',
                    '',
                    '**Expected output**',
                    '',
                    '```text',
                    '$ gh workflow view ci',
                    'build .................. ok   (18.4 kB flash, +112 B vs main)',
                    'unit tests ............. 128 passed, 0 failed, 94.1% lines',
                    'static analysis ........ cppcheck 0 warnings, clang-tidy 0',
                    'renode integration ..... boots, 1 kHz tick verified, CAN round-trip ok',
                    'bootloader ............. signed image accepted, tampered image REJECTED',
                    '```',
                    '',
                    '```text',
                    '$ ./tools/ota-demo.sh',
                    'bank A  v1.2.0  (running)',
                    'uploading v1.3.0 ....... signature ok      -> staged to bank B',
                    'reboot ................. bank B active, v1.3.0 running',
                    'uploading v1.4.0-evil .. signature INVALID -> rejected, bank A retained',
                    'power cut mid-write .... watchdog reboot, bank A still bootable',
                    '```',
                    '',
                    '**What makes it stand out**',
                    '',
                    'The **power-cut test**. Interrupting the update and showing the device still boots the old bank is',
                    'the thing a hiring manager who has shipped hardware will notice, because they have been burned by',
                    'it. Put that line in the README near the top.',
                  ].join('\n'),
                  criteria: [
                    'Rebuild the I2C and CAN layers test-first against a mocked bus',
                    'Reach meaningful branch coverage on error paths, not just the happy path',
                    'Run unit tests in GitHub Actions on every push, with a badge in the README',
                    'Add a Renode integration job that boots the real image and checks behaviour',
                    'Run a static analyser in the pipeline and fix or justify every finding',
                    'Report flash and RAM delta against main on every pull request',
                    'Build an A/B bootloader that verifies a signature before switching banks',
                    'Prove a tampered image is rejected and the previous bank still boots',
                    'Prove a power cut mid-update leaves the device bootable',
                  ],
                }},
      ],
    },

    /* ================= ELECTIVE TRACKS ================= */
    {
      title: 'Track A — Embedded Linux',
      elective: true,
      blurb: 'A different career track from MCU firmware: userspace, drivers, and building ' +
        'your own distribution.',
      topics: [
        { title: 'Embedded Linux Foundations', road: ['Operating Systems > Embedded Linux'],
          legacy: ['Embedded Operating Systems > GNU/Linux'] },
        { title: 'The Linux Kernel', road: ['Embedded Linux > Linux Kernel'] },
        { title: 'Device Drivers', road: ['Embedded Linux > Linux Device Drivers'] },
        { title: 'U-Boot', road: ['Embedded Linux > U-Boot'] },
        { title: 'Buildroot', road: ['Embedded Linux > Buildroot'] },
        { title: 'Yocto', road: ['Embedded Linux > Yocto'] },
        { title: 'Threads & IPC',
          road: ['Embedded Linux > Multithreading & Parallel Processing',
                 'Embedded Linux > Inter-Process Communication (IPC)'] },
        { title: 'Performance', road: ['Embedded Linux > High-Performance Computing (HPC)'] },
        { title: 'Qt', road: ['Embedded Linux > Qt Framework'] },
        { project: {
                  name: 'A Linux Image and a Driver You Wrote',
                  goal: 'Build a bootable embedded Linux system from source and put your own kernel module inside it.',
                  brief: [
                    '**What you are building**',
                    '',
                    'A minimal **Buildroot** image for an emulated ARM board that boots in QEMU to a shell, containing a',
                    '**character device driver you wrote** - exposing the same cell-voltage data as cellguard, so the',
                    'two projects tell one story.',
                    '',
                    '**Why this is worth showing**',
                    '',
                    'Embedded Linux is a separate job market from MCU firmware, and "I built the image from source and',
                    'wrote the driver in it" answers both halves of the interview. Because it runs in QEMU, a reviewer',
                    'can boot your system without a board.',
                    '',
                    '**Expected output**',
                    '',
                    '```text',
                    '$ make -C buildroot && ./run-qemu.sh',
                    'Booting Linux on physical CPU 0x0',
                    '...',
                    'cellguard: registered char device major 240',
                    'Welcome to cellguard-linux',
                    '# cat /dev/cellguard0',
                    'cell0=3.874V cell1=3.871V cell2=3.869V temp=25.0C',
                    '# dmesg | tail -2',
                    'cellguard: open() by pid 412',
                    'cellguard: 3 reads, 0 errors',
                    '```',
                    '',
                    '**What makes it stand out**',
                    '',
                    'Ship the whole thing as one script. `./run-qemu.sh` downloading nothing and booting straight to',
                    'your driver\'s output is far more convincing than a page of instructions, and it is the same',
                    '"a stranger can run it" property that makes the rest of your portfolio work.',
                  ].join('\n'),
                  criteria: [
                    'Build a minimal Buildroot image for an emulated ARM board',
                    'Boot it in QEMU and get to a shell',
                    'Write a character device driver and load it as a module',
                    'Read from your device node in userspace and show the output',
                    'Build the driver into the image so it loads at boot',
                    'Wrap the whole boot in a single script a reviewer can run',
                  ],
                }},
      ],
    },

    {
      title: 'Track B — Automotive & AUTOSAR',
      elective: true,
      blurb: 'Directly relevant to EV, BMS and vehicle-control work: the architecture, ' +
        'the buses and the safety process.',
      topics: [
        { title: 'AUTOSAR Architecture', road: ['AUTOSAR Architecture'] },
        { title: 'LIN, FlexRay & J1939',
          plus: [
            { title: 'LIN Bus Explained - A Simple Intro', type: 'Article', source: 'CSS Electronics',
              url: 'https://www.csselectronics.com/pages/lin-bus-protocol-intro-basics', beginner: true },
            { title: 'LIN (Local Interconnect Network)', type: 'Article', source: 'Wikipedia',
              url: 'https://en.wikipedia.org/wiki/Local_Interconnect_Network' },
            { title: 'FlexRay', type: 'Article', source: 'Wikipedia',
              url: 'https://en.wikipedia.org/wiki/FlexRay' },
            { title: 'SAE J1939 Explained - A Simple Intro', type: 'Article', source: 'CSS Electronics',
              url: 'https://www.csselectronics.com/pages/j1939-explained-simple-intro-tutorial' },
          ] },
        { title: 'Diagnostics (UDS & OBD-II)',
          plus: [
            { title: 'UDS Protocol - Unified Diagnostic Services Intro', type: 'Article', source: 'CSS Electronics',
              url: 'https://www.csselectronics.com/pages/uds-protocol-tutorial-unified-diagnostic-services', beginner: true },
            { title: 'OBD2 Explained - A Simple Intro', type: 'Article', source: 'CSS Electronics',
              url: 'https://www.csselectronics.com/pages/obd2-explained-simple-intro' },
            { title: 'Unified Diagnostic Services', type: 'Article', source: 'Wikipedia',
              url: 'https://en.wikipedia.org/wiki/Unified_Diagnostic_Services' },
          ] },
        { title: 'ISO 26262 & Functional Safety for Vehicles',
          plus: [
            { title: 'ISO 26262', type: 'Article', source: 'Wikipedia',
              url: 'https://en.wikipedia.org/wiki/ISO_26262', beginner: true },
            { title: 'Automotive Safety Integrity Level (ASIL)', type: 'Article', source: 'Wikipedia',
              url: 'https://en.wikipedia.org/wiki/Automotive_Safety_Integrity_Level' },
          ] },
        { project: {
                  name: 'The Safety Case: A BMS Node Under Test',
                  goal: 'Take cellguard to where it would have to be for a real vehicle: a defensible state machine, latching faults, and a bench that replays real traffic to prove it.',
                  brief: [
                    '**What you are building**',
                    '',
                    'The full battery-management application on top of everything you have built, plus a',
                    '**HIL-style test bench** that replays recorded CAN traffic and asserts the node responds correctly',
                    'and within its deadline.',
                    '',
                    '**Why this is worth showing**',
                    '',
                    'This is the piece that maps directly onto EV and automotive roles. A state machine with **latching**',
                    'faults and an explicit clear path is exactly what functional-safety work looks like, and a replay',
                    'bench is how those teams actually test.',
                    '',
                    '**Expected output**',
                    '',
                    '```text',
                    '$ ./bench/replay.sh logs/overvoltage_event.log',
                    't=0.000  IDLE      -> CHARGING     (charger present, all cells 3.6-4.0 V)',
                    't=4.120  cell 7 = 4.251 V  (limit 4.20 V)',
                    't=4.121  CHARGING  -> FAULT_OV     latched, contactor open, 1 ms after detect',
                    't=4.121  ASSERT ok: reaction time 1.0 ms  (deadline 10 ms)',
                    't=9.000  clear requested while cell still high -> REFUSED',
                    't=31.40  cell 7 = 4.05 V, clear requested -> FAULT_OV -> IDLE',
                    '',
                    '18 scenarios replayed: 18 passed',
                    '  overvoltage, undervoltage, overtemp, sensor dropout, CAN silence,',
                    '  contactor weld, watchdog starvation, brown-out during charge',
                    '```',
                    '',
                    '**What makes it stand out**',
                    '',
                    'The **fault table** in the README: every fault, its trigger threshold, its reaction deadline, what',
                    'the node does, and how it clears. One page. That table is the artefact a battery-systems engineer',
                    'will read first, and it shows you think about failure before features.',
                  ].join('\n'),
                  criteria: [
                    'Define the CAN message set: cell voltages, pack current, temperature, state',
                    'Implement idle / charge / discharge / fault as an explicit state machine',
                    'Make every fault latching, with a clear path that refuses while the cause persists',
                    'Give every fault a detection threshold and a reaction deadline',
                    'Add watchdog supervision that survives a hung task',
                    'Build a replay bench that drives recorded CAN logs and asserts the outcome',
                    'Cover at least 8 failure scenarios including sensor dropout and CAN silence',
                    'Publish the fault table: trigger, deadline, reaction, clear condition',
                  ],
                }},
      ],
    },

    {
      title: 'Track C — Edge AI & TinyML',
      elective: true,
      blurb: 'Running inference on a microcontroller — where it makes sense and where it does not.',
      topics: [
        { title: 'ML Fundamentals', road: ['Edge AI > AI & ML Basics', 'Learning Resources > Edge AI'] },
        { title: 'TensorFlow Lite for Microcontrollers', road: ['Edge AI > TensorFlow Lite'] },
        { title: 'TinyML', road: ['Edge AI > TinyML'] },
        { project: {
                  name: 'Anomaly Detection That Fits In The Budget',
                  goal: 'Add a tiny model that spots a failing cell - then report honestly whether it earns its flash.',
                  brief: [
                    '**What you are building**',
                    '',
                    'A small model that flags **anomalous cell behaviour** from the voltage and temperature history',
                    'cellguard already collects, quantised to int8 and running on the emulated MCU alongside everything',
                    'else.',
                    '',
                    '**Why this is worth showing**',
                    '',
                    'TinyML on a CV is usually a tutorial rerun on someone else\'s dataset. Attaching it to *your own*',
                    'firmware\'s real signal, and then measuring whether it fits, is engineering rather than a demo.',
                    '',
                    '**Expected output**',
                    '',
                    '```text',
                    '$ make ml-report',
                    'model: 3-layer MLP, 8x16x2, int8 quantised',
                    '  flash ............ 6.1 kB  (33% of remaining budget)',
                    '  RAM (arena) ...... 2.8 kB',
                    '  cycles/inference . 41 200  @16 MHz = 2.6 ms',
                    '  fits in 20 ms control period: YES (13% of budget)',
                    '',
                    'accuracy on held-out cells:',
                    '  float32 .......... 94.2%',
                    '  int8 quantised ... 92.8%   (-1.4 pts)',
                    '  false positives .. 0.6%  <- a false fault trip is expensive',
                    '```',
                    '',
                    '**What makes it stand out**',
                    '',
                    'The honest verdict. Ending the README with *"a fixed threshold on dV/dt catches 89% of these for',
                    '40 bytes and 12 cycles, so the model is not justified on this part - it becomes worth it above N',
                    'cells"* shows more judgement than any accuracy number. Engineers who say when not to use a',
                    'technique get hired.',
                  ].join('\n'),
                  criteria: [
                    'Train an anomaly-detection model on the cell data your firmware produces',
                    'Quantise to int8 and measure the accuracy you lost',
                    'Run it on the emulated MCU with TensorFlow Lite Micro',
                    'Measure flash, RAM arena and cycles per inference',
                    'Check it fits inside your existing control period and say by how much',
                    'Compare it against a simple threshold baseline on the same data',
                    'State plainly whether the model is justified, and under what conditions',
                  ],
                }},
      ],
    },

    {
      title: 'Track D — DSP & Control',
      elective: true,
      blurb: 'The maths layer: filtering real signals and closing control loops.',
      topics: [
        { title: 'DSP Basics & Filter Design',
          road: ['Digital Signal Processing > DSP Basics & Filter Design'],
          legacy: ['Embedded Software Layers > Application Layer > Domain Knowledge > Digital Signal Processing'] },
        { title: 'FFT', road: ['Digital Signal Processing > Discrete Fourier Transform / FFT'],
          legacy: ['Embedded Software Layers > Application Layer > Domain Knowledge > Digital Signal Processing > FFT'] },
        { title: 'Filters (FIR & IIR)',
          legacy: ['Embedded Software Layers > Application Layer > Domain Knowledge > Digital Signal Processing > Filters'] },
        { title: 'Control Theory', road: ['Learning Resources > Control Theory'] },
        { title: 'PID', road: ['Control Theory > PID Controller'],
          legacy: ['Embedded Software Layers > Application Layer > Domain Knowledge > Control Systems > PID'],
          shelf: true },
        { title: 'Modelling & Simulation', road: ['Control Theory > MATLAB / Simulink'] },
        { project: {
                  name: 'Estimation and Control, Inside The ISR',
                  goal: 'Add the maths a battery system actually needs - a filter and a control loop - written in fixed point and proven to fit the time budget.',
                  brief: [
                    '**What you are building**',
                    '',
                    'Two things cellguard needs: a **fixed-point IIR filter** cleaning the noisy current signal, and a',
                    '**PID loop** driving balancing current, with anti-windup and output clamping. Both run inside a',
                    'timer ISR with a measured cycle cost.',
                    '',
                    '**Why this is worth showing**',
                    '',
                    'Fixed-point DSP without an FPU, verified against a float reference and measured against a deadline,',
                    'is a genuinely uncommon skill. Anti-windup in particular is the detail that separates someone who',
                    'has read about PID from someone who has run one.',
                    '',
                    '**Expected output**',
                    '',
                    '```text',
                    '$ make control-report',
                    'IIR biquad, Q15, fc=20 Hz @1 kHz',
                    '  max error vs float64 reference .... 0.031%',
                    '  cycles/sample ..................... 148   (9.3 us @16 MHz)',
                    '',
                    'PID (kp=0.8 ki=0.12 kd=0.02), anti-windup: back-calculation',
                    '  step response: rise 240 ms, overshoot 4.1%, settle 620 ms',
                    '  saturated 8 s then released -> recovered in 310 ms (no windup)',
                    '  cycles/update ..................... 96    (6.0 us)',
                    '',
                    'total in 1 kHz ISR: 15.3 us of 1000 us budget (1.5%)',
                    '```',
                    '',
                    '**What makes it stand out**',
                    '',
                    'The **saturation recovery plot**. Drive the actuator into its limit, hold it, release, and show the',
                    'loop recovering without the integrator having wound up. Put the with/without-anti-windup curves',
                    'side by side - it is one image that proves you understand the failure mode.',
                  ].join('\n'),
                  criteria: [
                    'Implement a fixed-point IIR filter and check it against a float reference',
                    'Report the maximum error and the cycles per sample',
                    'Implement a PID loop with anti-windup and output clamping',
                    'Measure step response: rise time, overshoot and settling time',
                    'Drive the output into saturation, release, and show recovery without windup',
                    'Plot with and without anti-windup side by side',
                    'Run both inside the timer ISR and report the fraction of the budget used',
                  ],
                }},
      ],
    },

    {
      title: 'Appendix — Languages Beyond C',
      elective: true,
      shelf: true,
      blurb: 'Optional. C is the job; these come up increasingly often around it.',
      topics: [
        { title: 'C++ for Embedded',
          road: ['Programming Languages > C++', 'C++ > Additional resources from Bjarne Stroustrup, creator of C++'] },
        { title: 'Rust for Embedded', road: ['Programming Languages > Rust'] },
        { title: 'Python for Tooling & Test',
          road: ['Programming Languages > Python', 'Python > Python for Microcontrollers'] },
        { title: 'Zig', road: ['Programming Languages > Zig'] },
      ],
    },
  ],
};
